-- SCHEMA Creation File - Tested on MYSQL

DROP DATABASE IF EXISTS BACKEND;

CREATE DATABASE BACKEND;

DROP TABLE IF EXISTS BACKEND.CONTACT;

-- create
CREATE TABLE BACKEND.CONTACT(
  ID INT AUTO_INCREMENT,
  PHONE_NUMBER VARCHAR(15),
  EMAIL VARCHAR(255),
  LINKED_ID INT,
  LINK_PRECEDENCE ENUM('primary', 'secondary'),
  CREATED_AT DATETIME(3) NOT NULL DEFAULT NOW(3),
  UPDATED_AT DATETIME(3) NOT NULL DEFAULT NOW(3) ON UPDATE NOW(3),
  DELETED_AT DATETIME(3),
  CONSTRAINT PK_ID PRIMARY KEY (ID),
  CONSTRAINT UNIQ_PHONE_NUMBER_EMAIL UNIQUE (PHONE_NUMBER, EMAIL)
);

DESC BACKEND.CONTACT;